### PR TITLE
Added vector forms for hashes, fixes issue #214.

### PR DESCRIPTION
**Pull request by vinitkataria**

### CODE REVIEW

**Comment by piyush-kurur** [comment]
Please send the commits as separate commits so that I can be sure that the necessary changes have been done. Do not rebase -i it.

**Comment by piyush-kurur** [comment]
I have added comments to source lines. Can you make the above
mentioned changes quickly. I do not see too much of an issue
otherwise.

**Comment by vinitkataria** [comment]
Sir, I have made the changes. There was a typo in the safe version of `parseVector` in raaz-core package and due to it load-store tests were failing, I couldn't figure it out earlier.

**Comment by piyush-kurur** [comment]
I have added a few comments on simplifying the sha1 code. Those are applicable to the other hashes as well. So please fix them as well

**Comment by vinitkataria** [comment]
Updated.

**Comment by vinitkataria** [comment]
Updated.

**Comment by piyush-kurur** [comment]
Finally can you rebase to my master

**Comment by vinitkataria** [comment]
Rebased.

**Comment by piyush-kurur** [comment]
Closed in 17720b585f16c3d24ee7ff0859be90b1603892a5

**Pull request closed without merging**
