### PR TITLE
Wiping memory

### PR DESCRIPTION
**Pull request by piyush-kurur**
Better memory wipes.

### CODE REVIEW

**Comment by piyush-kurur** [comment]
@Mistuke can you review the use of SecureZeroMemory in the file core/cbits/raaz/core/memory.c. I wrote it up looking at the other functions that you had contributed. It does not seem to work on appveyor.

**Comment by Mistuke** [comment]
But looking quickly on my phone, you're first attempt was wrong because the return type of the function pointer is incorrect. 

You've reused `VirtualFunction` which is a `BOOL` result type (e.g. `Int`) while `SecureZeroMemory` has `void*`. My guess is this is corrupting the call frame.

Your second attempt is just a type :) You won't need to use the function pointer indeed if all supported version of GHC have that function defined. This wasn't the case for the ones I added so I had to use dynamic importing.

**Comment by piyush-kurur** [comment]
On Wed, Jan 02, 2019 at 06:36:09AM -0800, Tamar Christina wrote:
>
> But looking quickly on my phone, you're first attempt was wrong
> because the return type of the function pointer is incorrect.
> 
> You've reused `VirtualFunction` which is a `BOOL` result type
> (e.g. `Int`) while `SecureZeroMemory` has `void*`. My guess is this
> is corrupting the call frame.
>


Okey I will give it another try.


> Your second attempt is just a type :) You won't need to use the function pointer indeed if all supported version of GHC have that function defined. This wasn't the case for the ones I added so I had to use dynamic importing.
>

May be I was too optimisitic :-). I just noticed there is a semi-colon
missing. If that does not work out I will try the dynamic importing with
the change that you suggested.

Regards,

ppk

**Comment by piyush-kurur** [comment]
Okey that seems to work. thanks @Mistuke. Now I am getting more ambitious, can we remove the dynamic importing ? In any case we are going to only support ghc >= 8.2 because we need backpack.

**Comment by Mistuke** [comment]
> I am merging this change. @Mistuke if you do not mind (and once you are back from your holiday) can you simplify the other calls too if ghc-8.2+ supports them. You might want to add an entry in the appveyor.yml file build matrix to test it against older (i.e. 8.2._, 8.4._ series of ghcs).
> 

Oh sorry, completely forgot about this. 8.4 and 8.6 support it, I need to check 8.2. Will do that tomorrow and if so I'll make a PR.

**Comment by piyush-kurur** [comment]
On Mon, Feb 04, 2019 at 01:02:50PM -0800, Tamar Christina wrote:
> > I am merging this change. @Mistuke if you do not mind (and once you are back from your holiday) can you simplify the other calls too if ghc-8.2+ supports them. You might want to add an entry in the appveyor.yml file build matrix to test it against older (i.e. 8.2._, 8.4._ series of ghcs).
> > 
> 
> Oh sorry, completely forgot about this. 8.4 and 8.6 support it, I need to check 8.2. Will do that tomorrow and if so I'll make a PR.
> 

No worries. take your time.

**Pull request merged**
