### PR TITLE
Handwritten C implementations added to the mix

### PR DESCRIPTION
**Pull request by piyush-kurur**
We have introduces handwritten implementations again so as to compare it with that exposed by verse.
The output of the benchmarking code is now in csv for better comparison.

### CODE REVIEW

**Comment by piyush-kurur** [comment]
@Mistuke  I am not sure why but I have tried running benchmarks and it fails on appveryor. 
(Note, it is not a compilation failure). Do you have any pointers for fixing this ?

**Comment by Mistuke** [comment]
Do your benchmarks test Unicode characters?

**Comment by piyush-kurur** [comment]
Yeah okey I will supress that

**Comment by Mistuke** [comment]
You don't have to, change the console's codepage to UTF8. Windows's default codepage isn't a Unicode one.

Add
`chcp 65001`

somewhere in your AppVeyor script before running the tests.

That should work, if it doesn't then you may need to tell GHC about it too

`hSetEncoding stdout utf8`

though this shouldn't be needed as GHC defaults to the codepage of the console.

**Comment by Mistuke** [comment]
looks like you do need to set the encoding type in the tests as well. When the new I/O manager is in this should work out of the box, but for now you have to manually change the encoding.

**Comment by piyush-kurur** [comment]
@Mistuke thanks for the prompt help. Now the build is fixed.

**Comment by piyush-kurur** [comment]
Okey I have created an issue for this. Will try to fix this at some point of time.

**Pull request merged**
