### PR TITLE
Separating packages 

### PR DESCRIPTION
**Pull request by piyush-kurur**
The raaz packages are now split so that the signature files and actual implementations can be used externally. The result is a set of 4 packages `raaz-core`, `raaz-implementation-indef`, `raaz-implementation` and finally `raaz`.

### CODE REVIEW

**Comment by piyush-kurur** [comment]
@Mistuke can you give some feedback on this appveyor build failure. As far as I see it is a problem with the raaz-implementation-indef package.

**Comment by Mistuke** [comment]
@piyush-kurur I fear you might be hitting `MAX_PATH` 

```
> "C:\raaz\dist-newstyle\build\i386-windows\ghc-8.4.3\raaz-implementation-indef-0.3.0\raaz-implementation-indef-0.3.0-inplace+BwzXbLNCKzCDape3ArsWIb\build\raaz-implementation-indef-0.3.0-inplace+BwzXbLNCKzCDape3ArsWIb\autogen\".length
223
```

`openBinaryTempFileWithDefaultPermissions` takes a base path, and I think Cabal is supplying it with that string as the temp dir. which leaves it just ~20 chars for the filename. I think it's https://github.com/haskell/cabal/blob/6814d87a7acfa0568b94db58c40a6144c1799468/Cabal/Distribution/Simple/Configure.hs#L249 that's failing, so the filename will contain the full `package-id` so 20 chars isn't enough. 

This is fixed permanently in `GHC 8.6`, so a `cabal` built with that would just work, for now, you can try shortening your package name, dropping `implementation` from the name for instance frees 42 characters, which may be enough.

Looking at the source I don't see a straight forward way to work around this. May be worth opening a ticket for this, there may be an option to change the location of the `dist-newbuild` folder I'm not aware of..

**Comment by piyush-kurur** [comment]
Oh no this is the second time I am getting hit by this. Let me see if there is a better name for this package.

**Comment by Mistuke** [comment]
Ah I see `core` is short enough :) this should all be a thing of the past soon.

**Comment by piyush-kurur** [comment]
To be fair I too did not like the raaz-implementation-indef name. I wanted to export the signature directly from the core package but that is one think that you cannot currently do with backpack if you want to instantiate it with some package that depends on it.

**Pull request merged**
