### PR TITLE
Debian packaging for raaz (for launchpad testing)

### PR DESCRIPTION
**Pull request by sakshamsharma**
Still work in progress, since I've not yet figured out the complete details about running the tests (waiting on IRC on debian-haskell).

Steps to build and install the Raaz.* libraries on Debian based systems:
```
# Install stack, since cabal-debian doesn't install with cabal right now
mkdir ~/tmp && cd ~/tmp
wget https://www.stackage.org/stack/linux-x86_64
tar xvf linux-x86_64
<enter the new folder>
./stack install cabal-debian

cd ~ && mkdir debian_builds && cd debian_builds
cp -r ~/raaz haskell-raaz
tar czf haskell-raaz_0.0.2.orig.tar.gz haskell-raaz
cd haskell-raaz

debuild -us -uc
cd ..
dpkg -i <deb file>
```

`cabal-debian` seems to do most fo the heavy lifting

Reference: http://askubuntu.com/questions/146343/how-to-create-a-deb-package-that-installs-a-series-of-files#146353

For installing dependencies:
http://ask.debian.net/questions/how-to-install-a-package-s-build-dependencies

Much more refining left to do here.

### CODE REVIEW

**Comment by sakshamsharma** [comment]
Update: It might be nice if instead of keeping the debian sources here, we keep them in a separate repository (something like: [this](https://github.com/Bumblebee-Project/bumblebee-ppa) ). This is debatable though.

Also, right now we have to modify the `debian/` files (update, actually. Using `cabal-debian --official`) everytime someone does some major change.

**Comment by piyush-kurur** [comment]
Makes sense to have a different repository. In fact one could have a single repository for all the future raaz packages (for example the raaz-ssh package). 

I just wonder launchpad has these recipies which has I guess is a bzr repo in itself. I am not sure if git is supported for these recipies.

**Comment by sakshamsharma** [comment]
Well, the bumblebee repo above is in git. Also, I think I did see somewhere that git is now supported, not sure though. Also, the testing happens at the `.deb` building time (the `debuild -us -uc` command)

**Comment by piyush-kurur** [comment]
Yes git is supported now.

**Comment by piyush-kurur** [comment]
Let me know when you are done. I can try it on launchpad.

**Comment by sakshamsharma** [comment]
So the tests are run while building the deb file. I still haven't got around to reading the launchpad manual, so don't know it this is fine or not. Also, the files I've committed were generated for the current git HEAD. If they are needed for the 0.0.2 instead, they need to be regenerated using the above commands after checking out the version. Apparently there have been changes from 0.0.2 to HEAD which breaks the `debuild -us -uc` logic if one tries to build a different version than the version the `debian/` folder was generated for.

So if the above aren't any issues, then I think launchpad should be fine to try out now. I'll look into `debuild -S` later, to see if it has a way of allowing testing later on at the install phase.

**Comment by piyush-kurur** [comment]
As far as I understand all I need to do is to have a top level directory called debian and push it into the launchpad copy. I have already setup the recipe for building it. Launchpad is realy a stink when it comes to UI.

If you have a launchpad account let me know and I will add you to the raaz-crypto group there. I think it should be possible for you to test it out then

**Comment by sakshamsharma** [comment]
My launchpad account is `saksham`

**Comment by piyush-kurur** [comment]
I have added you to the raaz-crypto group on the launchpad. We can test your package out but I do not like the current solution because we have to keep the top level debian directory. Such a directory means indirectly taking up packaging responsibility of Debian/Ubuntu packaging. This would currently be a big distraction for a nacent project. We need to discuss this issue (may be in person)

**Comment by piyush-kurur** [comment]
Can you move the debian packing files to the raaz/raaz-debian repository instead? I think the correct way would be to keep the raaz repository clean. In the launchpad recipe we can nest raaz-debian at the location at the toplevel directory `debian`.

**Pull request closed without merging**
