### PR TITLE
Added the Curves package and reference impl. for EC25519

### PR DESCRIPTION
**Pull request by vinitkataria**

### CODE REVIEW

**Comment by vinitkataria** [comment]
Sir, 
I have made the relevant changes. The small change in raaz-modular was not needed so I got rid of that. 

For the CPortable implementation, curve25519-donna provides a portable C implementation and one specific to 64-bit machines (faster one). Currently, I have added functions for portable implementation only. I can add functions specific to 64-bit machines, if needed.

I will add the commits for tests and benchmarks if these look alright.

**Comment by piyush-kurur** [comment]
Please also include in this pull request the changes we discussed in
person:

1. Rename the c-functions so that there are no name collisions while
   linking. I suggest that we add a prefix raaz_ to them.

2. Using CPP macros to conditionally include the faster 64-bit
   implementation if the machine supports it.  Just one
   request. Please do this in a separate commit.

One clarification regarding point 2. Is it the case that the faster
64bit code works for any 64bit architecture or is it only for x86_64.

**Comment by piyush-kurur** [comment]
I gues this pull request is ready to merge can you comment?

**Comment by vinitkataria** [comment]
Yes sir. I made the changes some time back. 

And from their project's page, it seems that 64bit code should work for any 64-bit architecture (it doesn't seem specific to x86_64 : https://code.google.com/p/curve25519-donna/).

**Pull request merged**
