### PR TITLE
Reorganization

### PR DESCRIPTION
**Pull request by vinitkataria**
Reorganized the hierarchy, merged the tests, cleaned up old build scripts and added Stackage configuration in travis build script.

### CODE REVIEW

**Comment by piyush-kurur** [comment]
The tests are failing. We need to check what is going wrong.

**Comment by piyush-kurur** [comment]
In commit 0f44185, why is raaz-random/LICENSE being moved to src/cipher/LICENSE why is that. And once the package is a single package, there should only be one license file.

**Comment by vinitkataria** [comment]
The fails are happening because Criterion package version 1.1.0.0 that is set in Stackage does not support certain things that we are currently using in benchmarks (corresponding to the older version 0.8.0.2). I am working on that.

**Comment by piyush-kurur** [comment]
Can we have a quick resolution of this failures. If nothing works we
can suppress the benchmark code and get a version ready. We can then
revisit this when we clean stuff up (do not forget to raise a ticket
to document what is suppressed).

**Comment by vinitkataria** [comment]
I made the changes in benchmark code according to the latest Criterion package. That is resolved. 
I ran that on travis and everything is working fine for Stackage-LTS (GHC 7.8.4). (https://travis-ci.org/vinitkataria/raaz/builds/73455731)

Currently it is failing for Stackage-nightly (GHC 7.10.1 Cabal 1.22) and Haskell platform (GHC 7.6.3 Cabal 1.20). In case of GHC 7.6.3, there is some dependency conflict issue - some packages depend on unix-2.6.0.0 package and some others depend on unix-2.7.0.0. This is probably happening because we have extended the version limits of certain packages to newer ones (to accommodate Stackage). So some of the newer ones depend on newer versions while the older ones still depend on older versions. There have been issues of this sort in the past and people migrated to newer versions of GHC and Cabal to get rid of it.

Whereas, for Stackage-nightly the configuration process is running fine but the build is halting at some point without any explicit errors. That I am not able to figure out.

**Comment by piyush-kurur** [comment]
On Sun, Aug 02, 2015 at 11:04:01PM -0700, Vinit Kataria wrote:
> I made the changes in benchmark code according to the latest
> Criterion package. That is resolved.  I ran that on travis and
> everything is working fine for Stackage-LTS (GHC
> 7.8.4). (https://travis-ci.org/vinitkataria/raaz/builds/73455731)
> 
> Currently it is failing for Stackage-nightly (GHC 7.10.1 Cabal 1.22)
> and Haskell platform (GHC 7.6.3 Cabal 1.20). In case of GHC 7.6.3,
> there is some dependency conflict issue - some packages depend on
> unix-2.6.0.0 package and some others depend on unix-2.7.0.0.

If I believe correctly there is a Stackage for GHC 7.6.3 as well. We
can now ignore the haskell platform and do the testing for this
stackage version.

We do need to support 7.6.* series as the Debian stable currently is
at 7.6.* and will be so for some time. We do not actually need some of
the upper bounds, like for example base or quickcheck2 and I think it
is fine to remove them.

**Comment by piyush-kurur** [comment]
I am sorry to bring this up but can you quickly get the builds to
work. If the failure is only due to some benchmarks not compiling,
then we could as well comment them and get on the reorganisation. We
can then create an issue reminding to fix this issue.

Since you have already done the hard work, I think it is a pity if it
cannot get merged. I have few ideas to clean up the code base which is
stuck due to the reorganisation.

**Comment by vinitkataria** [comment]
Sir,

I am really sorry for the delay. I have moved to another city so I couldn't
get a proper internet connection earlier. I will make sure to get things
running by today evening.

**Comment by vinitkataria** [comment]
I tried to remove version upper bounds and also fixed some integer-gmp uses (some of the functions have been removed in the latest version of integer-gmp that is being used by Stackage-nightly). 

For GHC 7.6, it is still giving the same error of package conflicts between unix 2.6 and unix 2.7 (https://travis-ci.org/vinitkataria/raaz/jobs/74853445). I looked up the dependencies of all the packages on which our build (cabal file) depends on but there was none of them which depended on unix package. I cannot figure out why the two versions of unix package are being installed together. I looked up for similar bugs on the internet and people have asked to simply use newer versions of GHC and cabal. I also tried to look for stackage configuration for GHC 7.6 but I think they have stopped support for it. They now only provide config for 7.8 and 7.10.

Whereas, for GHC 7.10 case, everything is installing fine but when "cabal test" is done, it gives an error that cabal version was changed (https://travis-ci.org/vinitkataria/raaz/jobs/74853448). I don't understand why it is happening. Can I disable the running of tests and benchmarks on Travis for now? I will look into it further this week.

This is the latest version of my branch - https://github.com/vinitkataria/raaz/pull/2.

**Comment by vinitkataria** [comment]
If the running of tests and benchmarks is disabled (building is fine), GHC 7.10 also works fine (https://travis-ci.org/vinitkataria/raaz/builds/74861653).

**Comment by piyush-kurur** [comment]
On Sun, Aug 09, 2015 at 09:13:49PM -0700, Vinit Kataria wrote:
> I tried to remove version upper bounds and also fixed some
> integer-gmp uses (some of the functions have been removed in the
> latest version of integer-gmp that is being used by
> Stackage-nightly).
> 
> For GHC 7.6, it is still giving the same error of package conflicts
> between unix 2.6 and unix 2.7
> (https://travis-ci.org/vinitkataria/raaz/jobs/74853445). I looked up
> the dependencies of all the packages on which our build (cabal file)
> depends on but there was none of them which depended on unix
> package. I cannot figure out why the two versions of unix package
> are being installed together.

This is because cabal satisfies the constraints of two different
packages that we depend on using two different versions of unix.

Say we have two packages A and B that depends on different versions of
unix and they intern put contradicting requirements. We might even
need to bump up certain versions.

>I looked up for similar bugs on the internet and people have asked to
>simply use newer versions of GHC and cabal. I also tried to look for
>stackage configuration for GHC 7.6 but I think they have stopped
>support for it. They now only provide config for 7.8 and 7.10.


Okey then we should only build for 7.8 and 7.10. We will test it out
for 7.6 in a different way.

Regards,

ppk

**Comment by piyush-kurur** [comment]
On Sun, Aug 09, 2015 at 09:55:59PM -0700, Vinit Kataria wrote:
> If the running of tests and benchmarks is disabled (building is
> fine), GHC 7.10 also works fine
> (https://travis-ci.org/vinitkataria/raaz/builds/74861653).

I am not so worried about benchmarks right now but disabling all tests
in not a good idea because then we will not have any sanity check on
the code that is being commited. We need to be more careful. May be we
need to bump up certain package versions.

**Pull request closed without merging**
